### ISSUE TITLE
Web client: editable table view

### ISSUE THREAD

**Issue by orogenic** [orogenic/mabcs#13]
Add a click handler to every table cell which transforms the table cell into an editable field with a save button. When the user clicks the save button, the client sends a request to the server to commit the update to the database, and switches the cell back to its original data view.

This is straightforward for things like text and number inputs, but less straightforward for things like foreign key relationships, where the client may provide a dropdown of existing records, or allow the user to insert a new record into a related table and establish the relation to the record being edited.

**Comment by jonathan-mejia-deluna** [comment]
This is referring to the table of transactions, yes?

**Comment by orogenic** [comment]
Yes, the TransactionV1 table for now, which will also be modified soon FYI. Hopefully it will be largely reusable for other tables as well.

**Comment by jonathan-mejia-deluna** [comment]
It seems like every column is now editable from the client-side except for the receipt image. If a receipt data cell is clicked, then the user is prompted to submit a file from the local file system, but the text "No file chosen" remains even after selecting a file.
